version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: ${DJANGO_ENV:-development}
    ports:
      - "8000:8000"
    environment:
      # Django Configuration
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DEBUG=${DEBUG:-False}  # Default to False for security
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-config.settings}
      - DJANGO_DEBUG_TOOLBAR=${DJANGO_DEBUG_TOOLBAR:-1}
      - PYTHONPATH=${PYTHONPATH:-/app}

      # Redis Configuration
      - REDIS_URL=${REDIS_URL:-redis://127.0.0.1:6379/0}

      # Credex Core API Configuration
      - MYCREDEX_APP_URL=${MYCREDEX_APP_URL:-https://dev.mycredex.dev/}
      - CLIENT_API_KEY=${CLIENT_API_KEY}

      # WhatsApp Integration
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://graph.facebook.com/v17.0/}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_BUSINESS_ID=${WHATSAPP_BUSINESS_ID}
      - WHATSAPP_REGISTRATION_FLOW_ID=${WHATSAPP_REGISTRATION_FLOW_ID}
      - WHATSAPP_COMPANY_REGISTRATION_FLOW_ID=${WHATSAPP_COMPANY_REGISTRATION_FLOW_ID}

      # Development Settings
      - X_GITHUB_TOKEN=${X_GITHUB_TOKEN:-}
    volumes:
      - .:/app:cached
      - python-packages:/usr/local/lib/python3.10/site-packages/
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    network_mode: "service:redis"
    command: ./start_app.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git/
            - .venv/
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: requirements/dev.txt

  redis:
    image: redis:7-alpine
    user: root
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --bind 0.0.0.0
      --dir /redis

volumes:
  redis_data:
  python-packages:
