version: '3.8'

services:
  app:
    build:
      context: ..
      target: development
    volumes:
      - ./data:/app/data
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DJANGO_SECRET=local-secret-key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
