name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || 'staging' }}

    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup and Initialize Terraform Backend
        run: |
          echo "Current environment: ${ENVIRONMENT}"
          BUCKET_NAME="vimbiso-pay-terraform-state-${ENVIRONMENT}"
          TABLE_NAME="vimbiso-pay-terraform-state-lock-${ENVIRONMENT}"

          # Check if S3 bucket exists, create if it doesn't
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Creating S3 bucket: $BUCKET_NAME"
            aws s3api create-bucket --bucket "$BUCKET_NAME" --create-bucket-configuration LocationConstraint=af-south-1
            aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" --versioning-configuration Status=Enabled
            aws s3api put-bucket-encryption --bucket "$BUCKET_NAME" --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
          else
            echo "S3 bucket already exists: $BUCKET_NAME"
          fi

          # Check if DynamoDB table exists, create if it doesn't
          if ! aws dynamodb describe-table --table-name "$TABLE_NAME" >/dev/null 2>&1; then
            echo "Creating DynamoDB table: $TABLE_NAME"
            aws dynamodb create-table --table-name "$TABLE_NAME" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          else
            echo "DynamoDB table already exists: $TABLE_NAME"
          fi

          # Initialize Terraform
          cd terraform
          echo "Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${BUCKET_NAME}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=af-south-1" \
            -backend-config="dynamodb_table=${TABLE_NAME}"

      - name: Terraform Plan
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          # Add dummy value for required docker_image variable since it's not used by connectors module
          TF_VAR_docker_image: "dummy"
          # Add dummy values for required application variables
          TF_VAR_django_secret: "dummy"
          TF_VAR_mycredex_app_url: "dummy"
          TF_VAR_client_api_key: "dummy"
          TF_VAR_whatsapp_api_url: "dummy"
          TF_VAR_whatsapp_access_token: "dummy"
          TF_VAR_whatsapp_phone_number_id: "dummy"
        run: |
          cd terraform
          echo "Current environment: ${ENVIRONMENT}"
          echo "Planning Terraform changes..."
          terraform plan -input=false -out=tfplan -target=module.connectors

      - name: Terraform Apply
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          # Add dummy value for required docker_image variable since it's not used by connectors module
          TF_VAR_docker_image: "dummy"
          # Add dummy values for required application variables
          TF_VAR_django_secret: "dummy"
          TF_VAR_mycredex_app_url: "dummy"
          TF_VAR_client_api_key: "dummy"
          TF_VAR_whatsapp_api_url: "dummy"
          TF_VAR_whatsapp_access_token: "dummy"
          TF_VAR_whatsapp_phone_number_id: "dummy"
        run: |
          cd terraform
          echo "Current environment: ${ENVIRONMENT}"
          echo "Applying Terraform changes..."
          terraform apply -auto-approve -input=false tfplan

      - name: Print Infrastructure Outputs
        run: |
          cd terraform
          echo "Current environment: ${ENVIRONMENT}"
          echo "========================================"
          echo "Infrastructure Outputs:"
          echo "========================================"
          echo "VPC ID: $(terraform output -raw vpc_id)"
          echo "Private Subnet IDs: $(terraform output -json private_subnet_ids)"
          echo "Public Subnet IDs: $(terraform output -json public_subnet_ids)"
          echo "ECR Repository URL: $(terraform output -raw ecr_repository_url)"
          echo "Domain: $(terraform output -raw domain)"
          echo "========================================"
