name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches:
      - auto-deploy-setup

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH_PRIVATE_KEY secret
        run: |
         echo "SSH_PRIVATE_KEY secret exists: ${{ secrets.SSH_KEY != '' }}"
          echo "SSH_PRIVATE_KEY secret length: ${#{{ secrets.SSH_KEY }}}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
