name: Test SSH Key Format

on:
  workflow_dispatch:
  push:
    branches:
      - auto-deploy-setup

jobs:
  check_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH Key Secret Exists
        run: |
          if [[ -z "${{ secrets.SSH_KEY }}" ]]; then
            echo "SSH_KEY secret is empty or not set."
            exit 1
          fi

      - name: Check SSH Key Format
        run: |
          echo "${{ secrets.SSH_KEY }}" | grep -q "BEGIN [A-Z ]*PRIVATE KEY"
          if [[ $? -ne 0 ]]; then
            echo "SSH_KEY is not in the correct format."
            exit 1
          else
            echo "SSH_KEY is in the correct format."
          fi

      - name: Check SSH Key Length
        run: |
          KEY_LENGTH=$(echo "${{ secrets.SSH_KEY }}" | wc -c)
          if [[ $KEY_LENGTH -lt 1000 ]]; then
            echo "SSH_KEY appears to be too short. It might be incorrect."
            exit 1
          else
            echo "SSH_KEY length seems appropriate."
          fi

     
