name: Test SSH Key Format

on:
  workflow_dispatch:
  push:
    branches:
      - auto-deploy-setup

jobs:
  check_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH Key Secret Exists
        run: |
          if [[ -z "${{ secrets.SSH_KEY }}" ]]; then
            echo "SSH_KEY secret is empty or not set."
            exit 1
          fi

      - name: Create .ssh Directory
        run: |
          mkdir -p ~/.ssh

      - name: Save SSH Key to a File
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/temp_id_rsa
          chmod 600 ~/.ssh/temp_id_rsa

      - name: Attempt to Use SSH Key
        run: |
          ssh -i ~/.ssh/temp_id_rsa -o StrictHostKeyChecking=no -T git@github.com || true
          ssh -i ~/.ssh/temp_id_rsa -o StrictHostKeyChecking=no -T localhost || true

      - name: Clean Up
        run: |
          rm ~/.ssh/temp_id_rsa
