name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH_PRIVATE_KEY secret
        run: |
          echo "SSH_PRIVATE_KEY secret exists: ${{ secrets.SSH_KEY != '' }}"
          echo "SSH_PRIVATE_KEY secret length: ${{ secrets.SSH_KEY | length }}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
