name: Test SSH Key Format

on:
  workflow_dispatch:
  push:
    branches:
      - auto-deploy-setup

jobs:
  check_ssh_key:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH Key Secret Exists
        run: |
          if [[ -z "${{ secrets.SSH_KEY }}" ]]; then
            echo "SSH_KEY secret is empty or not set."
            exit 1
          fi

      - name: Print SSH Key
        run: |
          echo "SSH_KEY: ${{ secrets.SSH_KEY }}"

      - name: Check SSH Key Format
        run: |
          if ! echo "${{ secrets.SSH_KEY }}" | grep -q "BEGIN [A-Z ]*PRIVATE KEY"; then
            echo "SSH_KEY is not in the correct format."
            exit 1
          fi
          
      # rest of the steps...
